on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.LAUNCHBOT_INTERNAL_APP_ID }}
          private-key: ${{ secrets.LAUNCHBOT_INTERNAL_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          config-file: release-please-config.json
          token: ${{ steps.app-token.outputs.token }}

  release_python_client:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true'}}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Build Distribution
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1

  release_docker_image:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true'}}
    uses: ./.github/workflows/build-docker-images.yaml
    with:
      repository: launchflow
      environment: production
